sudo: required
services:
  - docker

before_install:
  - docker build -t kengonline/multi-container-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run kengonline/multi-container-app npm test -- --coverage

after_success:
  # Tag production images
  - docker build -t kengonline/multi-container-frontend ./frontend
  - docker build -t kengonline/multi-container-backend-server ./backend-server
  - docker build -t kengonline/multi-container-worker ./worker
  - docker build -t kengonline/multi-container-nginx ./nginx
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to repository
  - docker push kengonline/multi-container-frontend
  - docker push kengonline/multi-container-backend-server
  - docker push kengonline/multi-container-worker
  - docker push kengonline/multi-container-nginx
# deploy:
#   provider: elasticbeanstalk
#   region: ap-southeast-1
#   app: multi-container-docker
#   env: MultiContainerDocker-env
#   bucket_name: elasticbeanstalk-ap-southeast-1-179397784370
#   bucket_path: multi-container-docker
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
