sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISALBE_PROMPTS = 1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in bookstore-231807-e80e8d354e7a.json.enc -out bookstore-231807-e80e8d354e7a.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file bookstore-231807-e80e8d354e7a.json
  - gcloud config set project bookstore-231807
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kengonline/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run kengonline/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
