apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bookstore.business
  dnsNames:
    - api.bookstore.business
    - www.bookstore.business
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - api.bookstore.business
          - www.bookstore.business
